# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b51d89a542f71a3e0fee7fc1bc858625e036456885dfb730c303ed52619a486be3981b3a8e461d48d4905b2e838c096ff6ac6c6770c9457fd45ca4c5aab4da8e

test:
  secret_key_base: 94297573b5e6de7135f5c542b95ae1ba82786d3a0036a1e165f16799ad00448869f9f0ddd248d60cd46686c91a61e0df74623022aa50a877209a08224df9e1fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
